### ISSUE TITLE
local variable 'dr' referenced before assignment

### ISSUE THREAD

**Issue by thesourcerer8** [Hortofagos/International-Dollar#11]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "main.py", line 548, in win_button
    for bsm in dr[4:]:
UnboundLocalError: local variable 'dr' referenced before assignment

**Comment by Hortofagos** [comment]
This error code occurs when trying to open the "Win/Print" tab, without having generated a wallet. It has been fixed in the latest commit
