### ISSUE TITLE
Cryptographic API Misuse Vulnerability: Do not use constant salts for PBE

### ISSUE THREAD

**Issue by gxx777** [Hortofagos/International-Dollar#19]
Hello! 
First and foremost, I would like to express my sincere gratitude for your contributions to this project. 

### Description:
I have identified a security vulnerability in the International-Dollar project's use of constant salt for PBKDF  for key derivation by our cryptographic api misuse detector. The issue is that a constant salt is being used, which can lead to security vulnerabilities.

### Locations:
https://github.com/Hortofagos/International-Dollar/blob/main/wallet_encryption.py#L13
https://github.com/Hortofagos/International-Dollar/blob/main/wallet_decryption.py#L17

### References: 
[CWE-330: Use of Insufficiently Random Values](https://cwe.mitre.org/data/definitions/330.html)

### Suggested Fix:
 I would recommend using a secure random salt for PBKDF2 key derivation. Here's an example of how to generate a secure random salt:
```python
import os
salt = os.urandom(16)  # 16 bytes (128 bits) is a common choice for a salt length.
```

**Comment by Hortofagos** [comment]
I think adding a random salt is in this case useless.
