### ISSUE TITLE
tkextrafont version dependency

### ISSUE THREAD

**Issue by thesourcerer8** [Hortofagos/International-Dollar#8]
I am getting this error:
ERROR: Could not find a version that satisfies the requirement tkextrafont>=0.6.3 (from versions: 0.6.0, 0.6.1)
ERROR: No matching distribution found for tkextrafont>=0.6.3
Is the version 0.6.1 ok too?

**Comment by Hortofagos** [comment]
Thank you for submitting the issue. In fact there is no need for tkextrafont anymore. We forgot to delete it out of requirements.txt. The issue has been fixed.
